/// Flutter icons MyApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///

import 'package:flutter/widgets.dart';

class PetPal {
  PetPal._();

  static const _kFontFam = 'PetPal';

  static const IconData pets = const IconData(0xe800, fontFamily: _kFontFam);
}
